[setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm install --no-audit --no-fund"]

[phases.build]
cmds = ["npm run build:prod"]

[start]
cmd = "npx serve -s build -l ${PORT}"

[variables]
PORT = "3000"

